#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
from pathlib import Path
import v40_upgrade_campaign_stage_a as v40
from v41_baseline_stack_common import *
from v41_baseline_entry_value import evaluate_entry_layer
from v41_baseline_action_value import build_action_targets,evaluate_action_layer,choose_best_action
from v41_baseline_stack_economics import *

def main():
 ap=argparse.ArgumentParser();ap.add_argument('--v38-run-folder',required=True);ap.add_argument('--v36-predictions',required=True);ap.add_argument('--output-dir',required=True);a=ap.parse_args();out=Path(a.output_dir);out.mkdir(parents=True,exist_ok=True)
 m1,_,trades,meta,v36diag=v40.load_inputs(Path(a.v38_run_folder),Path(a.v36_predictions));tr=add_trade_sequence_features(trades);m1=attach_sequence_to_m1(m1,tr);entry,ef=evaluate_entry_layer(tr);states=build_action_targets(m1);v36=load_v36_calibration_table(Path(a.v36_predictions),tr);candidates,af=evaluate_action_layer(states,v36);actions=choose_best_action(candidates);stack=build_stack(tr,entry,m1,actions);sm,_=shadow_metrics(stack);audit,auditm=layer_audit(tr);seg=segments(tr);gate=aggregate_gate(ef,af,actions,sm,stack)
 summary={'schema':'v41_baseline_stack_action_value_stage_a_v1','baseline_architecture':{'candidate':CONTROL,'type':'causal_performance_weighted_mixture_of_rule_based_experts','experts':['EMA_skip20','MACD_gap10','BOS_FVG_gap8','Trend20_gap5','SlowMomentum_16h24h'],'router_state':'normalized_control_book_realized_R_EWMA','ewma_half_life':8,'router_threshold':0.0,'direction_owner':'selected_expert_signal_not_meta_router','known_gaps':['delayed_realized-R feedback','no direct opportunity-value model','sequence/churn only implicit','V36 state not integrated','exit intervention not action-value based']},'research_contract':{'entry_layer':'HGBRegressor expected-R; causal source/time/prior-completed-trade context; fixed keep60','action_layer':'HGBRegressor E(delta_R) + HGBClassifier P(delta_R>0); static/trail; fixed 20% calibration coverage','v36_layer':'accepted Transformer predictions chronology-calibrated; V36 not retrained','sequence_layer':'churn/exhaustion as soft features; hard rules diagnostic only','risk_changed':False,'extra_entries':0,'no_test_month_threshold_tuning':True},'accepted_exact_baseline':{'start_usd':40.0,'end_usd':107.43,'geo_month':.0858,'max_dd':.099,'trades':563},'aspirational_target':{'geo_month':.15,'target_end_usd_12m':40*(1.15**12),'gap_percentage_points':6.42},'inputs':meta,'gate':gate,'stack_metrics':sm.to_dict(orient='records'),'frozen_positive_evidence':{'V32_DeepMLP_keep60':{'status':'FROZEN_REFERENCE_NOT_RETUNED','geo_month':.076193,'max_dd':.073639,'trades':153,'avg_r':.325,'pf':1.8326,'baseline_geo_month_same_window':.076807},'V36_Transformer':{'status':'FROZEN_SEQUENCE_FEATURE','hold_auc':.675683,'protect_auc':.677066,'final_r_spearman':.514812},'V30_expected_R':{'status':'ARCHITECTURE_LEAD_NOT_FRESH_CONFIRMATION','lesson':'expected-R stronger than win/loss; family context matters'}},'rejected_layers_not_integrated':['generic cooldown','hard conjunctive quality gate','broad signal fusion','fixed range-to-family router','universal fast exit','V39 eventual-giveback target','V40 first-passage-only target'],'notes':['All V41 equity results are calibrated decision-tape shadow diagnostics and are NOT exact-MT5 PnL.','A Stage-A PASS only permits a frozen exact-MT5 Stage B; LIVE remains forbidden.','Targeted exhaustion/session rules are diagnostics and are not auto-integrated from same-sample observations.']}
 ef.to_csv(out/'v41_entry_fold_metrics.csv',index=False,lineterminator='\n');entry.to_csv(out/'v41_entry_scored_trades.csv',index=False,lineterminator='\n');af.to_csv(out/'v41_action_fold_metrics.csv',index=False,lineterminator='\n');candidates.to_csv(out/'v41_action_candidates.csv',index=False,lineterminator='\n');actions.to_csv(out/'v41_action_triggers.csv',index=False,lineterminator='\n');stack.to_csv(out/'v41_trade_stack_shadow.csv',index=False,lineterminator='\n');sm.to_csv(out/'v41_stack_metrics.csv',index=False,lineterminator='\n');audit.to_csv(out/'v41_layer_audit.csv',index=False,lineterminator='\n');auditm.to_csv(out/'v41_layer_audit_monthly.csv',index=False,lineterminator='\n');seg.to_csv(out/'v41_baseline_segments.csv',index=False,lineterminator='\n');v36diag.to_csv(out/'v41_v36_original_calibration_diagnostic.csv',index=False,lineterminator='\n');(out/'v41_baseline_stack_action_value_summary.json').write_text(json.dumps(summary,indent=2,ensure_ascii=False),encoding='utf-8');print(json.dumps({'status':gate['status'],'promotion_lane':gate['promotion_lane'],'entry_geo':gate['entry_shadow_geo_month'],'action_geo':gate['action_shadow_geo_month'],'stack_geo':gate['integrated_shadow_geo_month'],'baseline_geo':.0858,'target_geo':.15,'actions':len(actions)},indent=2));return 0
if __name__=='__main__':raise SystemExit(main())
